package corbaConversion;


/**
* corbaConversion/IConversionRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* lundi 27 novembre 2023 14 h 34 CET
*/

public interface IConversionRemoteOperations 
{
  double conversionMontant (double mt);
} // interface IConversionRemoteOperations
